// src/commands/apply.ts
// Apply command - stamp repositories with required standards artifacts

import { resolve, join, dirname } from "node:path";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { loadStandardsConfig } from "../core/config-loader.js";
import { STANDARDS_VERSION } from "../version.js";

/**
 * Options for the apply command.
 */
export interface ApplyOptions {
  /** Dry run - show what would change without making changes */
  dry_run?: boolean;

  /** Force overwrite existing files */
  force?: boolean;
}

/**
 * Record of a file that was or would be created/updated.
 */
export interface FileChange {
  /** Relative path to the file */
  path: string;

  /** Type of change */
  action: "created" | "updated" | "skipped" | "would_create" | "would_update";

  /** Reason for the action */
  reason: string;
}

/**
 * Result of the apply command.
 */
export interface ApplyReport {
  /** Whether the apply was a dry run */
  dry_run: boolean;

  /** Path to the repository */
  repository_path: string;

  /** Standards version applied */
  standards_version: string;

  /** Stack identifier */
  stack_id: string;

  /** List of file changes */
  changes: FileChange[];

  /** Summary statistics */
  summary: {
    created: number;
    updated: number;
    skipped: number;
  };

  /** When apply was executed (ISO 8601 UTC) */
  applied_at: string;
}

/**
 * Default .odd/standards.toml template.
 */
function getDefaultStandardsToml(stack: string, version: string): string {
  return `# Standards Configuration
# Generated by repo-standards v${STANDARDS_VERSION}

version = "${version}"
stack = "${stack}"

[[packs]]
id = "core"
enabled = true
`;
}

/**
 * Helper to process a single file for apply.
 */
function processConfigFile(
  repoPath: string,
  configFile: { path: string; content?: string; reason: string },
  options: ApplyOptions,
  version: string,
  changes: FileChange[],
  summary: { created: number; updated: number; skipped: number },
): void {
  const filePath = join(repoPath, configFile.path);

  if (!existsSync(filePath)) {
    if (!options.dry_run && configFile.content) {
      const fileDir = dirname(filePath);
      if (!existsSync(fileDir)) {
        mkdirSync(fileDir, { recursive: true });
      }
      writeFileSync(filePath, configFile.content, "utf8");
    }
    changes.push({
      path: configFile.path,
      action: options.dry_run ? "would_create" : "created",
      reason: configFile.reason,
    });
    if (!options.dry_run) summary.created++;
    return;
  }

  if (options.force && configFile.content) {
    const existingContent = readFileSync(filePath, "utf8");
    if (existingContent !== configFile.content) {
      if (!options.dry_run) {
        writeFileSync(filePath, configFile.content, "utf8");
      }
      changes.push({
        path: configFile.path,
        action: options.dry_run ? "would_update" : "updated",
        reason: `Updated to match standards v${version}`,
      });
      if (!options.dry_run) summary.updated++;
      return;
    }
    changes.push({
      path: configFile.path,
      action: "skipped",
      reason: "Content already matches",
    });
    summary.skipped++;
    return;
  }

  changes.push({
    path: configFile.path,
    action: "skipped",
    reason: "Already exists (use --force to overwrite)",
  });
  summary.skipped++;
}

/**
 * Apply standards artifacts to a repository.
 *
 * This command is idempotent: running twice produces identical results.
 *
 * @param path - Path to the repository
 * @param options - Apply options
 * @returns Apply report with list of changes
 */
export async function apply(
  path: string,
  options: ApplyOptions = {},
): Promise<ApplyReport> {
  const repoPath = resolve(path);
  const changes: FileChange[] = [];
  const summary = { created: 0, updated: 0, skipped: 0 };

  // Try to load existing config, or use defaults
  let config;
  try {
    config = loadStandardsConfig(repoPath);
  } catch {
    config = {
      version: STANDARDS_VERSION,
      stack: "typescript-js" as const,
      packs: [{ id: "core", enabled: true }],
      config_hash: "",
    };
  }

  // Ensure .odd directory exists
  const oddDir = join(repoPath, ".odd");
  if (!existsSync(oddDir)) {
    if (!options.dry_run) {
      mkdirSync(oddDir, { recursive: true });
    }
    changes.push({
      path: ".odd",
      action: options.dry_run ? "would_create" : "created",
      reason: "Standards configuration directory",
    });
    if (!options.dry_run) summary.created++;
  }

  // Apply standards.toml if missing
  const standardsTomlPath = join(repoPath, ".odd", "standards.toml");
  if (!existsSync(standardsTomlPath)) {
    const content = getDefaultStandardsToml(config.stack, config.version);
    if (!options.dry_run) {
      writeFileSync(standardsTomlPath, content, "utf8");
    }
    changes.push({
      path: ".odd/standards.toml",
      action: options.dry_run ? "would_create" : "created",
      reason: "Standards configuration file",
    });
    if (!options.dry_run) summary.created++;
  } else {
    changes.push({
      path: ".odd/standards.toml",
      action: "skipped",
      reason: "Already exists",
    });
    summary.skipped++;
  }

  // Check for common config files based on stack
  const configFiles = getStackConfigFiles(config.stack);
  for (const configFile of configFiles) {
    processConfigFile(
      repoPath,
      configFile,
      options,
      config.version,
      changes,
      summary,
    );
  }

  return {
    dry_run: options.dry_run || false,
    repository_path: repoPath,
    standards_version: config.version,
    stack_id: config.stack,
    changes,
    summary,
    applied_at: new Date().toISOString(),
  };
}

/**
 * Get standard config files for a stack.
 */
function getStackConfigFiles(
  stack: string,
): Array<{ path: string; content?: string; reason: string }> {
  switch (stack) {
    case "typescript-js":
      return [
        {
          path: ".prettierrc",
          content: JSON.stringify({ semi: true, singleQuote: false }, null, 2),
          reason: "Prettier configuration",
        },
        {
          path: ".editorconfig",
          content: `root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
`,
          reason: "EditorConfig for consistent formatting",
        },
      ];
    case "python":
      return [
        {
          path: ".editorconfig",
          content: `root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
`,
          reason: "EditorConfig for consistent formatting",
        },
        {
          path: "pyproject.toml",
          reason: "Python project configuration",
        },
      ];
    case "go":
      return [
        {
          path: ".editorconfig",
          content: `root = true

[*]
indent_style = tab
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
`,
          reason: "EditorConfig for consistent formatting",
        },
      ];
    default:
      return [];
  }
}
